# application.properties

spring.application.name=smart-civic-platform

# ===============================
# Server
# ===============================
server.port=${SERVER_PORT:8080}

# ===============================
# MongoDB
# ===============================
spring.mongodb.uri=${MONGODB_URI}

# ===============================
# JWT (used starting PHASE-2)
# ===============================
jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

# ===============================
# Frontend (used by CorsConfig)
# ===============================
frontend.url=${FRONTEND_URL}

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===============================
# Logging
# ===============================
logging.level.com.sr.smart_civic_platform=DEBUG
logging.level.org.springframework.security=INFO